### ISSUE TITLE
setup_tigramite_cython_code.py gives error under macOS

### ISSUE THREAD

**Issue by zrehder** [jakobrunge/tigramite_old#2]
under macOS Sierra and python2.7 with home-brew running 
`python setup_tigramite_cython_code.py build_ext --inplace`
 gave me:

running build_ext
building 'tigramite_src.tigramite_cython_code' extension
clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c tigramite_cython_code.c -o build/temp.macosx-10.12-x86_64-2.7/tigramite_cython_code.o
tigramite_cython_code.c:444:10: fatal error: 'numpy/arrayobject.h' file not found
#include "numpy/arrayobject.h"
         ^
1 error generated.
error: command 'clang' failed with exit status 1

It seemed to be a known error and changing the file to
from distutils.core import setup, Extension
from Cython.Build import cythonize
import numpy

setup(
    ext_modules = [
        Extension("tigramite_cython_code", ["tigramite_cython_code.c"],
            include_dirs=[numpy.get_include()]),
        ],
)

worked fine for me.

**Comment by jakobrunge** [comment]
Thanks, I'll change that!
